name: Platform Issue
description: Report dakboard site issue.
labels: ["Platform"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the issue?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1) …\n2) …\n3) …"
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: false

